name = "devsgowhere-telegram"
main = "src/index.ts"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2025-09-20"

[triggers]
crons = ["0 9 * * mon-sun"] 

[observability]
enabled = true

[vars]
TARGET_URL = "https://devsgowhere.com"
TELEGRAM_API_URL = "https://api.telegram.org"
CHANNEL_NAME = "@DevsGoWhere"